#requires -Version 5.1
<#
  ssh-fix.ps1  (self-healing)
  Fixes the most common causes of "sshd installed but refuses connections"
  on Windows 11 behind UCloud:
    1. missing/empty host keys   -> ssh-keygen -A
    2. ListenAddress pinned to 127.0.0.1 only -> 0.0.0.0
    3. broken Match Group administrators (localized group name on zh-Windows)
    4. service not running / not Automatic
    5. Windows Firewall blocking 22
  Then self-tests via loopback. If loopback OK but outside still fails,
  it migrates sshd to a clean high port and tells you the UCloud step.
  ASCII-only by design (RDP clipboard mangles non-ASCII).
  Result: %USERPROFILE%\Desktop\ssh-fix-result.txt
#>

$ErrorActionPreference = 'Continue'
$out = Join-Path $env:USERPROFILE 'Desktop\ssh-fix-result.txt'
$L = New-Object System.Collections.Generic.List[string]
function Sec($t){ $L.Add(''); $L.Add("=== $t ===") }
function W($t){ $L.Add([string]$t) }
function Rep($k,$v){ $L.Add("$k : $v") }

$rand = [guid]::NewGuid().ToString('N').Substring(0,8)
$NewPort = 35390

Sec "RUN"
W ("Time     : " + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss K'))
W ("Computer : " + $env:COMPUTERNAME)

$prog = "$env:WINDIR\System32\OpenSSH"
$sshdexe = "$prog\sshd.exe"
$keydir  = "$env:ProgramData\ssh"
$cfg     = "$keydir\sshd_config"

# ------------------------------------------------- 1. CAPABILITY
Sec "1. OPENSSH CAPABILITY"
$cap = Get-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction SilentlyContinue
if (-not $cap) { W "  Get-WindowsCapability returned nothing (odd)." }
elseif ($cap.State -ne 'Installed') {
    W "  State = $($cap.State), installing..."
    try { $r = Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction Stop; W ("  Install result: " + $r.RestartNeeded) }
    catch { W ("  Install FAILED: " + $_.Exception.Message) }
} else { W "  State = Installed" }

# ------------------------------------------------- 2. HOST KEYS
Sec "2. HOST KEYS"
try {
    if (Test-Path $keydir) {
        $hk = Get-ChildItem $keydir -Filter 'ssh_host_*' -ErrorAction SilentlyContinue
        $valid = $hk | Where-Object { $_.Length -gt 256 }
        W ("  found host key files: " + $hk.Count + ", size>256: " + $valid.Count)
        if ($valid.Count -eq 0) {
            W "  No valid host keys -> regenerating (ssh-keygen -A)"
            & "$prog\ssh-keygen.exe" -A | Out-Null
            $hk2 = Get-ChildItem $keydir -Filter 'ssh_host_*' -ErrorAction SilentlyContinue
            W ("  after regen: " + $hk2.Count + " files")
        }
    } else { W "  key dir missing" }
} catch { W ("  host key step error: " + $_.Exception.Message) }

# ------------------------------------------------- 3. CONFIG REWRITE
Sec "3. SSHD CONFIG"
$backup = "$cfg.bak-$rand"
$needRewrite = $false
if (Test-Path $cfg) {
    $txt = Get-Content $cfg -Raw
    if ($txt -match 'ListenAddress\s+127\.0\.0\.1') { $needRewrite = $true; W "  BAD: ListenAddress pinned to 127.0.0.1 only" }
    if ($txt -match 'Match Group') {
        $g = ($txt -split 'Match Group')[-1].Split([Environment]::NewLine)[0].Trim()
        $ng = (Get-LocalGroup -Name 'administrators*' -ErrorAction SilentlyContinue | Select-Object -First 1).Name
        if ($g -and $ng -and $g -notmatch [regex]::Escape($ng)) {
            $needRewrite = $true; W ("  BAD: Match Group name '$g' != localized group '$ng' (zh-Windows break)")
        }
    }
} else { $needRewrite = $true; W "  sshd_config missing" }

if ($needRewrite) {
    try {
        if (Test-Path $cfg) { Copy-Item $cfg $backup -Force; W ("  backup -> " + (Split-Path $backup -Leaf)) }
        $newcfg = @(
            '# generated by ssh-fix.ps1',
            'Port 22',
            'AddressFamily any',
            'ListenAddress 0.0.0.0',
            'PermitRootLogin no',
            'PubkeyAuthentication yes',
            'PasswordAuthentication yes',
            'AuthorizedKeysFile .ssh/authorized_keys',
            'Subsystem sftp sftp-server',
            'LogLevel DEBUG3'
        ) -join [Environment]::NewLine
        Set-Content -Path $cfg -Value $newcfg -Encoding ASCII -Force
        W "  rewrote sshd_config (clean, no localized Match block)"
    } catch { W ("  config rewrite FAILED: " + $_.Exception.Message) }
} else { W "  config looks fine, left as-is" }

# ------------------------------------------------- 4. FIREWALL (local)
Sec "4. WINDOWS FIREWALL (local)"
try {
    if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
            -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 | Out-Null
        W "  created rule OpenSSH-Server-In-TCP (22)"
    } else { Enable-NetFirewallRule -Name 'OpenSSH-Server-In-TCP'; W "  enabled rule OpenSSH-Server-In-TCP" }
} catch { W ("  firewall step error: " + $_.Exception.Message) }

# ------------------------------------------------- 5. SERVICE
Sec "5. SERVICE"
try {
    Set-Service -Name sshd -StartupType Automatic -ErrorAction Stop
    Restart-Service sshd -Force -ErrorAction Stop
    Start-Sleep -Seconds 3
    W ("  sshd: " + (Get-Service sshd).Status + " / Automatic")
} catch { W ("  service step error: " + $_.Exception.Message) }

# ------------------------------------------------- 6. LOOPBACK SELF-TEST
Sec "6. LOOPBACK TEST (127.0.0.1:22)"
$loopOK = $false
$loopBanner = ''
try {
    $job = Start-Job -ScriptBlock {
        $c = New-Object System.Net.Sockets.TcpClient
        $c.ReceiveTimeout = 8000; $c.SendTimeout = 8000
        $c.Connect('127.0.0.1', 22)
        $s = $c.GetStream(); $buf = New-Object byte[] 256
        $n = $s.Read($buf, 0, 256); $c.Close()
        [System.Text.Encoding]::ASCII.GetString($buf, 0, $n)
    }
    $r = Receive-Job $job -Wait -Timeout 20
    Remove-Job $job -Force -ErrorAction SilentlyContinue
    if ($r) { $loopOK = $true; $loopBanner = $r.Trim() }
} catch { W ("  loopback error: " + $_.Exception.Message) }
W ("  LOOPBACK = " + $(if ($loopOK) { 'OK -> ' + $loopBanner } else { 'FAIL (sshd still not greeting)' }))

# ------------------------------------------------- 7. HIGH-PORT MIGRATION IF NEEDED
$migrated = $false
if ($loopOK) {
    Rep "VERDICT" "LOOPBACK_OK_EXTERNAL_BLOCKED_MIGRATE"
    Sec "7. HIGH-PORT MIGRATION (UCloud-safe)"
    W "  Loopback works -> sshd itself is healthy. Outside failure means UCloud interferes with port 22."
    W "  Migrating sshd to port $NewPort ..."
    try {
        (Get-Content $cfg) -replace '^Port 22','Port ' + $NewPort | Set-Content $cfg
        if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP-35390' -ErrorAction SilentlyContinue)) {
            New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP-35390' -DisplayName 'OpenSSH Server (sshd 35390)' `
                -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort $NewPort | Out-Null
        }
        Restart-Service sshd -Force
        Start-Sleep -Seconds 3
        $l2 = Get-NetTCPConnection -State Listen -LocalPort $NewPort -ErrorAction SilentlyContinue
        W ("  listening on $NewPort : " + [bool]$l2)
        $migrated = $true
        W "  NEXT STEP: in UCloud console, add TCP $NewPort to firewall (same place as 35389), then test from Mac:"
        W "    ssh -p $NewPort administrator@165.154.135.98"
    } catch { W ("  migration error: " + $_.Exception.Message) }
} else {
    Rep "VERDICT" "SSHD_INTERNAL_BROKEN_REVIEW_ABOVE"
    W ""
    W "  sshd still not greeting even on loopback. Check section 2/3 output above."
    W "  Most likely: host key regen failed, or config still invalid (run sshd -t manually)."
}

# ------------------------------------------------- TITLE + SAVE
$title = $(if ($migrated) {"SSH-MIGRATED-PORT-$NewPort"} elseif ($loopOK) {"SSH-OK-USE-35390"} else {"SSH-STILL-BROKEN"})
try { [Console]::Title = $title } catch {}

$L | Set-Content -Path $out -Encoding UTF8
W ""
W ("WINDOW_TITLE = $title")
W ("RESULT_FILE  = $out")
Write-Host ""
Write-Host "WINDOW_TITLE = $title"
Write-Host "RESULT_FILE  = $out"
